/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SchoolId = IDL.Text;
export const TeacherId = IDL.Text;
export const TrainingId = IDL.Text;
export const Review = IDL.Record({
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'schoolId' : SchoolId,
  'rating' : IDL.Nat,
});
export const School = IDL.Record({
  'id' : SchoolId,
  'name' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'name' : IDL.Text,
  'schoolId' : SchoolId,
  'specialization' : IDL.Text,
});
export const Training = IDL.Record({
  'id' : TrainingId,
  'hours' : IDL.Nat,
  'description' : IDL.Text,
  'schoolId' : SchoolId,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([SchoolId, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addSchool' : IDL.Func(
      [SchoolId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text, SchoolId], [], []),
  'addTraining' : IDL.Func([TrainingId, IDL.Nat, IDL.Text, SchoolId], [], []),
  'getReviewsForSchool' : IDL.Func([SchoolId], [IDL.Vec(Review)], ['query']),
  'getSchool' : IDL.Func([SchoolId], [School], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [Teacher], ['query']),
  'getTeachersBySchool' : IDL.Func([SchoolId], [IDL.Vec(Teacher)], ['query']),
  'getTraining' : IDL.Func([TrainingId], [Training], ['query']),
  'getTrainingsBySchool' : IDL.Func([SchoolId], [IDL.Vec(Training)], ['query']),
  'searchSchoolsByName' : IDL.Func([IDL.Text], [IDL.Vec(School)], ['query']),
  'seedSchools' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SchoolId = IDL.Text;
  const TeacherId = IDL.Text;
  const TrainingId = IDL.Text;
  const Review = IDL.Record({
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'schoolId' : SchoolId,
    'rating' : IDL.Nat,
  });
  const School = IDL.Record({
    'id' : SchoolId,
    'name' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'name' : IDL.Text,
    'schoolId' : SchoolId,
    'specialization' : IDL.Text,
  });
  const Training = IDL.Record({
    'id' : TrainingId,
    'hours' : IDL.Nat,
    'description' : IDL.Text,
    'schoolId' : SchoolId,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([SchoolId, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addSchool' : IDL.Func(
        [SchoolId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text, SchoolId], [], []),
    'addTraining' : IDL.Func([TrainingId, IDL.Nat, IDL.Text, SchoolId], [], []),
    'getReviewsForSchool' : IDL.Func([SchoolId], [IDL.Vec(Review)], ['query']),
    'getSchool' : IDL.Func([SchoolId], [School], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [Teacher], ['query']),
    'getTeachersBySchool' : IDL.Func([SchoolId], [IDL.Vec(Teacher)], ['query']),
    'getTraining' : IDL.Func([TrainingId], [Training], ['query']),
    'getTrainingsBySchool' : IDL.Func(
        [SchoolId],
        [IDL.Vec(Training)],
        ['query'],
      ),
    'searchSchoolsByName' : IDL.Func([IDL.Text], [IDL.Vec(School)], ['query']),
    'seedSchools' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };