/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'featuredImageUrl' : [] | [string],
  'excerpt' : [] | [string],
}
export interface Review {
  'reviewerName' : string,
  'comment' : string,
  'schoolId' : SchoolId,
  'rating' : bigint,
}
export interface School {
  'id' : SchoolId,
  'country' : [] | [string],
  'city' : [] | [string],
  'name' : string,
  'state' : [] | [string],
  'videoUrl' : [] | [string],
  'location' : string,
}
export type SchoolId = string;
export interface Teacher {
  'id' : TeacherId,
  'name' : string,
  'schoolId' : SchoolId,
  'specialization' : string,
}
export type TeacherId = string;
export interface Training {
  'id' : TrainingId,
  'hours' : bigint,
  'description' : string,
  'schoolId' : SchoolId,
}
export type TrainingId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[SchoolId, string, bigint, string], undefined>,
  'addTeacher' : ActorMethod<[TeacherId, string, string, SchoolId], undefined>,
  'addTraining' : ActorMethod<
    [TrainingId, bigint, string, SchoolId],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'createSchool' : ActorMethod<
    [
      SchoolId,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteSchool' : ActorMethod<[SchoolId], undefined>,
  'deleteTeacher' : ActorMethod<[TeacherId], undefined>,
  'deleteTraining' : ActorMethod<[TrainingId], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReviewsForSchool' : ActorMethod<[SchoolId], Array<Review>>,
  'getSchool' : ActorMethod<[SchoolId], [] | [School]>,
  'getSchoolsByLocation' : ActorMethod<
    [[] | [string], [] | [string], [] | [string]],
    Array<School>
  >,
  'getTeacher' : ActorMethod<[TeacherId], [] | [Teacher]>,
  'getTeachersBySchool' : ActorMethod<[SchoolId], Array<Teacher>>,
  'getTraining' : ActorMethod<[TrainingId], [] | [Training]>,
  'getTrainingsBySchool' : ActorMethod<[SchoolId], Array<Training>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSchoolsByName' : ActorMethod<[string], Array<School>>,
  'updateBlogPost' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateSchool' : ActorMethod<
    [
      SchoolId,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateTeacher' : ActorMethod<
    [TeacherId, string, string, SchoolId],
    undefined
  >,
  'updateTraining' : ActorMethod<
    [TrainingId, bigint, string, SchoolId],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];