/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SchoolId = IDL.Text;
export const TeacherId = IDL.Text;
export const TrainingId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Review = IDL.Record({
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'schoolId' : SchoolId,
  'rating' : IDL.Nat,
});
export const School = IDL.Record({
  'id' : SchoolId,
  'country' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'videoUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'name' : IDL.Text,
  'schoolId' : SchoolId,
  'specialization' : IDL.Text,
});
export const Training = IDL.Record({
  'id' : TrainingId,
  'hours' : IDL.Nat,
  'description' : IDL.Text,
  'schoolId' : SchoolId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([SchoolId, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text, SchoolId], [], []),
  'addTraining' : IDL.Func([TrainingId, IDL.Nat, IDL.Text, SchoolId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'createSchool' : IDL.Func(
      [
        SchoolId,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteSchool' : IDL.Func([SchoolId], [], []),
  'deleteTeacher' : IDL.Func([TeacherId], [], []),
  'deleteTraining' : IDL.Func([TrainingId], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReviewsForSchool' : IDL.Func([SchoolId], [IDL.Vec(Review)], ['query']),
  'getSchool' : IDL.Func([SchoolId], [IDL.Opt(School)], ['query']),
  'getSchoolsByLocation' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(School)],
      ['query'],
    ),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
  'getTeachersBySchool' : IDL.Func([SchoolId], [IDL.Vec(Teacher)], ['query']),
  'getTraining' : IDL.Func([TrainingId], [IDL.Opt(Training)], ['query']),
  'getTrainingsBySchool' : IDL.Func([SchoolId], [IDL.Vec(Training)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSchoolsByName' : IDL.Func([IDL.Text], [IDL.Vec(School)], ['query']),
  'updateBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSchool' : IDL.Func(
      [
        SchoolId,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text, SchoolId], [], []),
  'updateTraining' : IDL.Func(
      [TrainingId, IDL.Nat, IDL.Text, SchoolId],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SchoolId = IDL.Text;
  const TeacherId = IDL.Text;
  const TrainingId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Review = IDL.Record({
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'schoolId' : SchoolId,
    'rating' : IDL.Nat,
  });
  const School = IDL.Record({
    'id' : SchoolId,
    'country' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'videoUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'name' : IDL.Text,
    'schoolId' : SchoolId,
    'specialization' : IDL.Text,
  });
  const Training = IDL.Record({
    'id' : TrainingId,
    'hours' : IDL.Nat,
    'description' : IDL.Text,
    'schoolId' : SchoolId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([SchoolId, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text, SchoolId], [], []),
    'addTraining' : IDL.Func([TrainingId, IDL.Nat, IDL.Text, SchoolId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'createSchool' : IDL.Func(
        [
          SchoolId,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteSchool' : IDL.Func([SchoolId], [], []),
    'deleteTeacher' : IDL.Func([TeacherId], [], []),
    'deleteTraining' : IDL.Func([TrainingId], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReviewsForSchool' : IDL.Func([SchoolId], [IDL.Vec(Review)], ['query']),
    'getSchool' : IDL.Func([SchoolId], [IDL.Opt(School)], ['query']),
    'getSchoolsByLocation' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(School)],
        ['query'],
      ),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
    'getTeachersBySchool' : IDL.Func([SchoolId], [IDL.Vec(Teacher)], ['query']),
    'getTraining' : IDL.Func([TrainingId], [IDL.Opt(Training)], ['query']),
    'getTrainingsBySchool' : IDL.Func(
        [SchoolId],
        [IDL.Vec(Training)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSchoolsByName' : IDL.Func([IDL.Text], [IDL.Vec(School)], ['query']),
    'updateBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSchool' : IDL.Func(
        [
          SchoolId,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [TeacherId, IDL.Text, IDL.Text, SchoolId],
        [],
        [],
      ),
    'updateTraining' : IDL.Func(
        [TrainingId, IDL.Nat, IDL.Text, SchoolId],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };