/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface School {
  'id' : SchoolId,
  'name' : string,
  'videoUrl' : [] | [string],
  'location' : string,
}
export type SchoolId = string;
export interface Teacher {
  'id' : TeacherId,
  'name' : string,
  'schoolId' : SchoolId,
  'specialization' : string,
}
export type TeacherId = string;
export interface Training {
  'id' : TrainingId,
  'hours' : bigint,
  'description' : string,
  'schoolId' : SchoolId,
}
export type TrainingId = string;
export interface _SERVICE {
  'addSchool' : ActorMethod<
    [SchoolId, string, string, [] | [string]],
    undefined
  >,
  'addTeacher' : ActorMethod<[TeacherId, string, string, SchoolId], undefined>,
  'addTraining' : ActorMethod<
    [TrainingId, bigint, string, SchoolId],
    undefined
  >,
  'getSchool' : ActorMethod<[SchoolId], School>,
  'getTeacher' : ActorMethod<[TeacherId], Teacher>,
  'getTeachersBySchool' : ActorMethod<[SchoolId], Array<Teacher>>,
  'getTraining' : ActorMethod<[TrainingId], Training>,
  'getTrainingsBySchool' : ActorMethod<[SchoolId], Array<Training>>,
  'searchSchoolsByName' : ActorMethod<[string], Array<School>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];